use_frameworks!

platform :ios, '8.0'

target 'Rudder-Adjust_Example' do
  pod 'Rudder-Adjust', :path => '../'

  target 'Rudder-Adjust_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
